-- NyumbaFasta Accounting System
-- Run in Supabase SQL Editor

-- ── Income Records ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS income_records (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Source type
  source            TEXT NOT NULL,
  -- 'subscription' | 'contact_unlock' | 'boost_listing' | 'extra_listing' | 'other'

  -- Source reference (ID from the originating table — idempotency key)
  source_ref_id     UUID NOT NULL,

  -- Optional link to payments audit table (may be null — table is partially populated)
  payment_id        UUID,

  -- Foreign keys to other tables
  dalali_id         UUID REFERENCES users(id) ON DELETE SET NULL,
  listing_id        UUID REFERENCES listings(id) ON DELETE SET NULL,

  -- Amounts
  amount_tzs        DECIMAL(15,2) NOT NULL,
  platform_fee_tzs  DECIMAL(15,2) DEFAULT 0,
  -- AzamPay ~1% fee (applied at report time, not deducted from dalali)
  net_amount_tzs    DECIMAL(15,2) NOT NULL,

  -- Details
  description       TEXT,
  reference_number  TEXT,
  payment_method    TEXT,
  -- 'Mpesa' | 'AirtelMoney' | 'Tigopesa' | 'Halopesa'

  -- Period fields (denormalized for fast reporting)
  transaction_date  DATE NOT NULL,
  month             INTEGER,   -- 1-12
  year              INTEGER,
  week              INTEGER,   -- 1-52

  -- Status
  status            TEXT DEFAULT 'confirmed',
  -- 'confirmed' | 'pending' | 'refunded' | 'disputed'

  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW(),

  -- Prevent duplicate recording of the same source transaction
  UNIQUE(source, source_ref_id)
);

-- ── Expense Records ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS expense_records (
  id               UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Category
  category         TEXT NOT NULL,
  -- 'hosting' | 'api_costs' | 'marketing' | 'legal' | 'staff' | 'software' | 'banking' | 'other'

  subcategory      TEXT,
  -- 'vercel' | 'supabase' | 'anthropic' | 'meta_ads' | 'whatsapp_api' | 'resend' etc

  -- Amounts
  amount_tzs       DECIMAL(15,2) NOT NULL,
  amount_usd       DECIMAL(10,2),
  exchange_rate    DECIMAL(10,2),
  -- TZS per USD used for conversion

  -- Details
  description      TEXT NOT NULL,
  vendor           TEXT,
  receipt_url      TEXT,
  reference_number TEXT,
  payment_method   TEXT,
  -- 'mpesa' | 'bank_transfer' | 'card' | 'cash'

  -- Period fields
  expense_date     DATE NOT NULL,
  month            INTEGER,
  year             INTEGER,
  week             INTEGER,

  -- Recurring
  is_recurring     BOOLEAN DEFAULT false,
  recurring_period TEXT,
  -- 'monthly' | 'annual' | 'weekly'

  -- Status
  status           TEXT DEFAULT 'paid',
  -- 'paid' | 'pending' | 'cancelled'

  -- Added by (admin user)
  added_by         UUID REFERENCES users(id) ON DELETE SET NULL,

  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ── Financial Summaries (cached, regenerated by cron) ──────────────────────
CREATE TABLE IF NOT EXISTS financial_summaries (
  id                     UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  period                 TEXT NOT NULL,      -- 'daily' | 'weekly' | 'monthly'
  period_date            DATE NOT NULL,      -- first day of period

  -- Income breakdown
  total_income_tzs       DECIMAL(15,2) DEFAULT 0,
  subscription_income    DECIMAL(15,2) DEFAULT 0,
  contact_unlock_income  DECIMAL(15,2) DEFAULT 0,
  boost_listing_income   DECIMAL(15,2) DEFAULT 0,
  extra_listing_income   DECIMAL(15,2) DEFAULT 0,
  other_income           DECIMAL(15,2) DEFAULT 0,

  -- Expense breakdown
  total_expenses_tzs     DECIMAL(15,2) DEFAULT 0,
  hosting_expenses       DECIMAL(15,2) DEFAULT 0,
  api_expenses           DECIMAL(15,2) DEFAULT 0,
  marketing_expenses     DECIMAL(15,2) DEFAULT 0,
  legal_expenses         DECIMAL(15,2) DEFAULT 0,
  staff_expenses         DECIMAL(15,2) DEFAULT 0,
  other_expenses         DECIMAL(15,2) DEFAULT 0,

  -- Profit/Loss
  gross_profit_tzs       DECIMAL(15,2) DEFAULT 0,
  net_profit_tzs         DECIMAL(15,2) DEFAULT 0,
  profit_margin          DECIMAL(5,2)  DEFAULT 0,

  -- Platform fees paid to AzamPay
  azampay_fees_tzs       DECIMAL(15,2) DEFAULT 0,

  -- Counts
  total_transactions     INTEGER DEFAULT 0,
  new_subscriptions      INTEGER DEFAULT 0,
  renewed_subscriptions  INTEGER DEFAULT 0,
  contact_unlocks_count  INTEGER DEFAULT 0,
  active_dalali_count    INTEGER DEFAULT 0,

  -- Growth vs previous period
  income_growth_percent  DECIMAL(5,2),
  expense_growth_percent DECIMAL(5,2),

  generated_at           TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(period, period_date)
);

-- ── Recurring Expenses (auto-added monthly) ────────────────────────────────
CREATE TABLE IF NOT EXISTS recurring_expenses (
  id               UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  category         TEXT NOT NULL,
  subcategory      TEXT,
  description      TEXT NOT NULL,
  vendor           TEXT,
  amount_tzs       DECIMAL(15,2) NOT NULL,
  amount_usd       DECIMAL(10,2),
  payment_method   TEXT,
  recurring_period TEXT DEFAULT 'monthly',
  -- 'monthly' | 'annual' | 'weekly'
  next_due_date    DATE NOT NULL,
  is_active        BOOLEAN DEFAULT true,
  added_by         UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ── Indexes ────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_ir_source        ON income_records(source);
CREATE INDEX IF NOT EXISTS idx_ir_date          ON income_records(transaction_date DESC);
CREATE INDEX IF NOT EXISTS idx_ir_month_year    ON income_records(year, month);
CREATE INDEX IF NOT EXISTS idx_ir_dalali        ON income_records(dalali_id);
CREATE INDEX IF NOT EXISTS idx_er_category      ON expense_records(category);
CREATE INDEX IF NOT EXISTS idx_er_date          ON expense_records(expense_date DESC);
CREATE INDEX IF NOT EXISTS idx_er_month_year    ON expense_records(year, month);
CREATE INDEX IF NOT EXISTS idx_fs_period        ON financial_summaries(period, period_date);

-- ── Disable RLS (admin-only data, accessed via service role) ───────────────
ALTER TABLE income_records      DISABLE ROW LEVEL SECURITY;
ALTER TABLE expense_records     DISABLE ROW LEVEL SECURITY;
ALTER TABLE financial_summaries DISABLE ROW LEVEL SECURITY;
ALTER TABLE recurring_expenses  DISABLE ROW LEVEL SECURITY;

-- ── Seed recurring expenses (update amounts to real values in dashboard) ───
INSERT INTO recurring_expenses
  (category, subcategory, description, vendor,
   amount_tzs, amount_usd, recurring_period, next_due_date)
VALUES
  ('hosting',   'vercel',       'Vercel Pro Hosting',      'Vercel',    52000, 20, 'monthly',
    DATE_TRUNC('month', NOW() + INTERVAL '1 month')::DATE),
  ('hosting',   'supabase',     'Supabase Database',       'Supabase',  26000, 10, 'monthly',
    DATE_TRUNC('month', NOW() + INTERVAL '1 month')::DATE),
  ('api_costs', 'anthropic',    'Anthropic Claude API',    'Anthropic', 52000, 20, 'monthly',
    DATE_TRUNC('month', NOW() + INTERVAL '1 month')::DATE),
  ('api_costs', 'whatsapp_api', 'WhatsApp Business API',   'Meta',          0,  0, 'monthly',
    DATE_TRUNC('month', NOW() + INTERVAL '1 month')::DATE),
  ('software',  'resend',       'Resend Email Service',    'Resend',        0,  0, 'monthly',
    DATE_TRUNC('month', NOW() + INTERVAL '1 month')::DATE)
ON CONFLICT DO NOTHING;
